In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Read the csv file into a pandas DataFrame
df = pd.read_csv("../data/SnowData.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df

,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,County Name
0,1/1/2000,Apishapa,4.1,0.4,12.0,0.0,10000,24.0,37.33062,-105.06749,Huerfano
1,1/2/2000,Apishapa,4.1,0.0,12.0,0.0,10000,18.0,37.33062,-105.06749,Huerfano
2,1/3/2000,Apishapa,4.1,0.0,12.0,0.0,10000,6.0,37.33062,-105.06749,Huerfano
3,1/4/2000,Apishapa,4.1,0.0,15.0,3.0,10000,21.0,37.33062,-105.06749,Huerfano
4,1/5/2000,Apishapa,4.5,0.4,14.0,-1.0,10000,24.0,37.33062,-105.06749,Huerfano
...,...,...,...,...,...,...,...,...,...,...,...
814973,5/13/2021,Zirkel,10.3,0.2,21.0,2.0,9340,46.0,40.79488,-106.59535,Jackson
814974,5/14/2021,Zirkel,8.4,-1.9,18.0,-3.0,9340,45.0,40.79488,-106.59535,Jackson
814975,5/15/2021,Zirkel,7.2,-1.2,17.0,-1.0,9340,46.0,40.79488,-106.59535,Jackson
814976,5/16/2021,Zirkel,6.1,-1.1,15.0,-2.0,9340,45.0,40.79488,-106.59535,Jackson
814977,5/17/2021,Zirkel,5.0,-1.1,12.0,-3.0,9340,42.0,40.79488,-106.59535,Jackson

In [ ]:
# df['Date'] = pd.to_datetime(df.Date)
# df['Date'] = df['Date'].dt.strftime('%Y/%m/%d')
# df

In [ ]:
# df['Date'] = pd.to_numeric(df.Date.str.replace('/',''))
# df

In [ ]:
# df['Date']=df['Date'].astype('string')
# df['Date']

In [8]:
df['Date'].apply(len)

0         8
1         8
2         8
3         8
4         8
         ..
814973    8
814974    8
814975    8
814976    8
814977    8
Name: Date, Length: 664621, dtype: int64

In [9]:
#drop year to get commonality of dates within data set
df['Date']=df['Date'].str[4:]
df.head(50)

,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,County Name
0,0101,Apishapa,4.1,0.4,12.0,0.0,10000,24.0,37.33062,-105.06749,Huerfano
1,0102,Apishapa,4.1,0.0,12.0,0.0,10000,18.0,37.33062,-105.06749,Huerfano
2,0103,Apishapa,4.1,0.0,12.0,0.0,10000,6.0,37.33062,-105.06749,Huerfano
3,0104,Apishapa,4.1,0.0,15.0,3.0,10000,21.0,37.33062,-105.06749,Huerfano
4,0105,Apishapa,4.5,0.4,14.0,-1.0,10000,24.0,37.33062,-105.06749,Huerfano
8,0109,Apishapa,4.6,0.1,14.0,-1.0,10000,15.0,37.33062,-105.06749,Huerfano
9,0110,Apishapa,4.6,0.0,14.0,0.0,10000,26.0,37.33062,-105.06749,Huerfano
10,0111,Apishapa,4.8,0.2,13.0,-1.0,10000,35.0,37.33062,-105.06749,Huerfano
11,0112,Apishapa,5.0,0.2,13.0,0.0,10000,33.0,37.33062,-105.06749,Huerfano
12,0113,Apishapa,5.0,0.0,13.0,0.0,10000,30.0,37.33062,-105.06749,Huerfano
13,0114,Apishapa,5.0,0.0,13.0,0.0,10000,34.0,37.33062,-105.06749,Huerfano
14,0115,Apishapa,5.0,0.0,13.0,0.0,10000,36.0,37.33062,-105.06749,Huerfano
15,0116,Apishapa,5.0,0.0,13.0,0.0,10000,41.0,37.33062,-105.06749,Huerfano
16,0117,Apishapa,5.0,0.0,12.0,-1.0,10000,40.0,37.33062,-105.06749,Huerfano
17,0118,Apishapa,4.9,-0.1,12.0,0.0,10000,39.0,37.33062,-105.06749,Huerfano
18,0119,Apishapa,4.7,-0.2,10.0,-2.0,10000,36.0,37.33062,-105.06749,Huerfano
19,0120,Apishapa,4.5,-0.2,9.0,-1.0,10000,36.0,37.33062,-105.06749,Huerfano
20,0121,Apishapa,4.5,0.0,7.0,-2.0,10000,31.0,37.33062,-105.06749,Huerfano
21,0122,Apishapa,4.6,0.1,9.0,2.0,10000,25.0,37.33062,-105.06749,Huerfano
22,0123,Apishapa,4.4,-0.2,9.0,0.0,10000,22.0,37.33062,-105.06749,Huerfano
23,0124,Apishapa,4.3,-0.1,8.0,-1.0,10000,30.0,37.33062,-105.06749,Huerfano
24,0125,Apishapa,4.5,0.2,8.0,0.0,10000,30.0,37.33062,-105.06749,Huerfano
25,0126,Apishapa,4.6,0.1,8.0,0.0,10000,28.0,37.33062,-105.06749,Huerfano
30,0131,Apishapa,5.1,0.0,15.0,0.0,10000,20.0,37.33062,-105.06749,Huerfano
33,0203,Apishapa,5.1,0.0,12.0,-2.0,10000,34.0,37.33062,-105.06749,Huerfano
34,0204,Apishapa,5.1,0.0,11.0,-1.0,10000,23.0,37.33062,-105.06749,Huerfano
35,0205,Apishapa,5.1,0.0,11.0,0.0,10000,34.0,37.33062,-105.06749,Huerfano
36,0206,Apishapa,5.1,0.0,10.0,-1.0,10000,29.0,37.33062,-105.06749,Huerfano
37,0207,Apishapa,5.1,0.0,11.0,1.0,10000,29.0,37.33062,-105.06749,Huerfano
38,0208,Apishapa,5.1,0.0,11.0,0.0,10000,38.0,37.33062,-105.06749,Huerfano
39,0209,Apishapa,5.1,0.0,10.0,-1.0,10000,34.0,37.33062,-105.06749,Huerfano
40,0210,Apishapa,5.1,0.0,10.0,0.0,10000,31.0,37.33062,-105.06749,Huerfano
41,0211,Apishapa,5.1,0.0,10.0,0.0,10000,28.0,37.33062,-105.06749,Huerfano
42,0212,Apishapa,5.1,0.0,10.0,0.0,10000,27.0,37.33062,-105.06749,Huerfano
43,0213,Apishapa,5.3,0.2,10.0,0.0,10000,22.0,37.33062,-105.06749,Huerfano
44,0214,Apishapa,5.3,0.0,10.0,0.0,10000,35.0,37.33062,-105.06749,Huerfano
45,0215,Apishapa,5.2,-0.1,9.0,-1.0,10000,33.0,37.33062,-105.06749,Huerfano
46,0216,Apishapa,4.9,-0.3,8.0,-1.0,10000,32.0,37.33062,-105.06749,Huerfano
47,0217,Apishapa,4.9,0.0,8.0,0.0,10000,25.0,37.33062,-105.06749,Huerfano
48,0218,Apishapa,4.9,0.0,9.0,1.0,10000,23.0,37.33062,-105.06749,Huerfano
49,0219,Apishapa,4.9,0.0,9.0,0.0,10000,28.0,37.33062,-105.06749,Huerfano
50,0220,Apishapa,4.8,-0.1,9.0,0.0,10000,35.0,37.33062,-105.06749,Huerfano
51,0221,Apishapa,4.6,-0.2,8.0,-1.0,10000,39.0,37.33062,-105.06749,Huerfano
52,0222,Apishapa,4.5,-0.1,8.0,0.0,10000,30.0,37.33062,-105.06749,Huerfano
53,0223,Apishapa,3.9,-0.6,8.0,0.0,10000,32.0,37.33062,-105.06749,Huerfano
54,0224,Apishapa,3.8,-0.1,6.0,-2.0,10000,28.0,37.33062,-105.06749,Huerfano
55,0225,Apishapa,3.8,0.0,9.0,3.0,10000,12.0,37.33062,-105.06749,Huerfano
56,0226,Apishapa,3.1,-0.7,8.0,-1.0,10000,22.0,37.33062,-105.06749,Huerfano
57,0227,Apishapa,3.6,0.5,7.0,-1.0,10000,37.0,37.33062,-105.06749,Huerfano
58,0228,Apishapa,4.0,0.4,6.0,-1.0,10000,31.0,37.33062,-105.06749,Huerfano

In [10]:
df.dtypes

Date                                               string
Station Name                                       object
Snow Water Equivalent (in) Start of Day Values    float64
Change In Snow Water Equivalent (in)              float64
Snow Depth (in) Start of Day Values               float64
Change In Snow Depth (in)                         float64
Elevation (ft)                                      int64
Air Temperature Average (degF)                    float64
Latitude                                          float64
Longitude                                         float64
County Name                                        object
dtype: object

In [12]:
one_hot = pd.get_dummies(df['Station Name'])
# Drop column as it is now encoded
data_df = df.drop('Station Name',axis = 1)
# Join the encoded df
data_df = data_df.join(one_hot)
data_df

,Date,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,County Name,...,Vail Mountain,Vallecito,Wager Gulch,Weminuche Creek,Whiskey Ck,Wild Basin,Willow Creek Pass,Willow Park,Wolf Creek Summit,Zirkel
0,0101,4.1,0.4,12.0,0.0,10000,24.0,37.33062,-105.06749,Huerfano,...,0,0,0,0,0,0,0,0,0,0
1,0102,4.1,0.0,12.0,0.0,10000,18.0,37.33062,-105.06749,Huerfano,...,0,0,0,0,0,0,0,0,0,0
2,0103,4.1,0.0,12.0,0.0,10000,6.0,37.33062,-105.06749,Huerfano,...,0,0,0,0,0,0,0,0,0,0
3,0104,4.1,0.0,15.0,3.0,10000,21.0,37.33062,-105.06749,Huerfano,...,0,0,0,0,0,0,0,0,0,0
4,0105,4.5,0.4,14.0,-1.0,10000,24.0,37.33062,-105.06749,Huerfano,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814973,0513,10.3,0.2,21.0,2.0,9340,46.0,40.79488,-106.59535,Jackson,...,0,0,0,0,0,0,0,0,0,1
814974,0514,8.4,-1.9,18.0,-3.0,9340,45.0,40.79488,-106.59535,Jackson,...,0,0,0,0,0,0,0,0,0,1
814975,0515,7.2,-1.2,17.0,-1.0,9340,46.0,40.79488,-106.59535,Jackson,...,0,0,0,0,0,0,0,0,0,1
814976,0516,6.1,-1.1,15.0,-2.0,9340,45.0,40.79488,-106.59535,Jackson,...,0,0,0,0,0,0,0,0,0,1
814977,0517,5.0,-1.1,12.0,-3.0,9340,42.0,40.79488,-106.59535,Jackson,...,0,0,0,0,0,0,0,0,0,1

In [13]:
one_hot = pd.get_dummies(data_df['County Name'])
# Drop column as it is now encoded
clean_df = data_df.drop('County Name',axis = 1)
# Join the encoded df
clean_df = clean_df.join(one_hot)
clean_df

,Date,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,Apishapa,...,Park,Pitkin,Rio Blanco,Rio Grande,Routt,Saguache,San Juan,San Miguel,Summit,Teller
0,0101,4.1,0.4,12.0,0.0,10000,24.0,37.33062,-105.06749,1,...,0,0,0,0,0,0,0,0,0,0
1,0102,4.1,0.0,12.0,0.0,10000,18.0,37.33062,-105.06749,1,...,0,0,0,0,0,0,0,0,0,0
2,0103,4.1,0.0,12.0,0.0,10000,6.0,37.33062,-105.06749,1,...,0,0,0,0,0,0,0,0,0,0
3,0104,4.1,0.0,15.0,3.0,10000,21.0,37.33062,-105.06749,1,...,0,0,0,0,0,0,0,0,0,0
4,0105,4.5,0.4,14.0,-1.0,10000,24.0,37.33062,-105.06749,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814973,0513,10.3,0.2,21.0,2.0,9340,46.0,40.79488,-106.59535,0,...,0,0,0,0,0,0,0,0,0,0
814974,0514,8.4,-1.9,18.0,-3.0,9340,45.0,40.79488,-106.59535,0,...,0,0,0,0,0,0,0,0,0,0
814975,0515,7.2,-1.2,17.0,-1.0,9340,46.0,40.79488,-106.59535,0,...,0,0,0,0,0,0,0,0,0,0
814976,0516,6.1,-1.1,15.0,-2.0,9340,45.0,40.79488,-106.59535,0,...,0,0,0,0,0,0,0,0,0,0
814977,0517,5.0,-1.1,12.0,-3.0,9340,42.0,40.79488,-106.59535,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
clean_df.to_csv('../data/SnowDataEncoded.csv')