In [3]:
#import dependencies
import pandas as pd
import numpy as np
import glob
import os

In [8]:
#bring in file path
path = r'../Data/exp_data'
#use glob to read through all files
all_files=glob.glob(path + "/*.csv")
#create empty list to fill with csv data
li =[]
#create for loop to reach through each file and append to li
for filename in all_files:
    snowDataDf=pd.read_csv(filename, index_col=None, header=0)
    li.append(snowDataDf)

snowframe = pd.concat(li, axis=0, ignore_index=True)
snowframe

,Date,Station Name,Station Id,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Air Temperature Observed (degF) Start of Day Values,Barometric Pressure (inch_Hg) Start of Day Values,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,Unnamed: 19
0,2000-01-01,Apishapa,303,4.1,0.4,12.0,0.0,31.0,NaN,7.4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-01-02,Apishapa,303,4.1,0.0,12.0,0.0,19.0,NaN,7.4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-01-03,Apishapa,303,4.1,0.0,12.0,0.0,13.0,NaN,7.4,0.3,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-01-04,Apishapa,303,4.1,0.0,15.0,3.0,1.0,NaN,7.7,0.0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-01-05,Apishapa,303,4.5,0.4,14.0,-1.0,27.0,NaN,7.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799144,2020-12-27,Zirkel,1033,6.0,0.4,25.0,3.0,22.0,NaN,9.0,0.2,0.2,NaN,NaN,33.0,NaN,34.0,35.0,NaN,NaN
799145,2020-12-28,Zirkel,1033,6.2,0.2,31.0,6.0,10.0,NaN,9.2,0.5,0.5,NaN,NaN,33.0,NaN,34.0,35.0,NaN,NaN
799146,2020-12-29,Zirkel,1033,6.7,0.5,32.0,1.0,19.0,NaN,9.7,0.0,0.0,NaN,NaN,33.0,NaN,34.0,35.0,NaN,NaN
799147,2020-12-30,Zirkel,1033,6.7,0.0,32.0,0.0,11.0,NaN,9.7,0.0,0.0,NaN,NaN,33.0,NaN,34.0,35.0,NaN,NaN
799148,2020-12-31,Zirkel,1033,6.7,0.0,30.0,-2.0,18.0,NaN,9.7,0.0,0.0,NaN,NaN,33.0,NaN,34.0,35.0,NaN,NaN

In [9]:
cleanSnowDf=snowframe.drop(['Unnamed: 19'],axis=1)
cleanSnowDf.head()

,Date,Station Name,Station Id,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Air Temperature Observed (degF) Start of Day Values,Barometric Pressure (inch_Hg) Start of Day Values,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
0,2000-01-01,Apishapa,303,4.1,0.4,12.0,0.0,31.0,NaN,7.4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-01-02,Apishapa,303,4.1,0.0,12.0,0.0,19.0,NaN,7.4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-01-03,Apishapa,303,4.1,0.0,12.0,0.0,13.0,NaN,7.4,0.3,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-01-04,Apishapa,303,4.1,0.0,15.0,3.0,1.0,NaN,7.7,0.0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-01-05,Apishapa,303,4.5,0.4,14.0,-1.0,27.0,NaN,7.7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
len(cleanSnowDf.index)

799149

In [11]:
# orderedSnowDf=cleanSnowDf[['Date','Station Name','Snow Water Equivalent (in) Start of Day Values','Change In Snow Water Equivalent (in)',
#                                             'Snow Depth (in) Start of Day Values','Change In Snow Depth (in)','Elevation (ft)','Air Temperature Average (degF)',
#                                             'Latitude','Longitude','County Name']]
# orderedSnowDf.head(15)

In [13]:
cleanSnowDf.to_csv(r'../Data/SnowData_exp.csv')

469610