In [1]:
from sklearn import tree
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_csv(os.path.join("../data/bulk_data.csv"))
# df=df.replace([np.inf, -np.inf], np.nan, inplace=True)
df=df.fillna(0)
df.head()

,Unnamed: 0,Unnamed: 0_x,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),...,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
0,0,0.0,2000-01-01,Apishapa,4.1,0.4,12.0,0.0,10000.0,24.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1.0,2000-01-02,Apishapa,4.1,0.0,12.0,0.0,10000.0,18.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2.0,2000-01-03,Apishapa,4.1,0.0,12.0,0.0,10000.0,6.0,...,7.4,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,3.0,2000-01-04,Apishapa,4.1,0.0,15.0,3.0,10000.0,21.0,...,7.7,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4.0,2000-01-05,Apishapa,4.5,0.4,14.0,-1.0,10000.0,24.0,...,7.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df=df[df['Station Name']== "Buffalo Park"]
df

,Unnamed: 0,Unnamed: 0_x,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),...,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
2562,2562,11144.0,2000-01-01,Buffalo Park,4.3,0.0,0.0,0.0,9240.0,17.0,...,5.2,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2563,2563,11145.0,2000-01-02,Buffalo Park,4.5,0.2,0.0,0.0,9240.0,12.0,...,5.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2564,2564,11146.0,2000-01-03,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,3.0,...,5.5,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2565,2565,11147.0,2000-01-04,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,13.0,...,5.6,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2566,2566,11148.0,2000-01-05,Buffalo Park,4.7,0.2,0.0,0.0,9240.0,12.0,...,5.8,0.1,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761812,761812,763457.0,2020-12-27,Buffalo Park,3.7,0.2,19.0,2.0,9240.0,16.0,...,3.7,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761813,761813,763458.0,2020-12-28,Buffalo Park,3.8,0.1,20.0,1.0,9240.0,15.0,...,3.8,0.4,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761814,761814,763459.0,2020-12-29,Buffalo Park,4.2,0.4,22.0,2.0,9240.0,12.0,...,4.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761815,761815,763460.0,2020-12-30,Buffalo Park,4.2,0.0,22.0,0.0,9240.0,2.0,...,4.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761816,761816,763461.0,2020-12-31,Buffalo Park,4.2,0.0,22.0,0.0,9240.0,18.0,...,4.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df['Change In Snow Depth (in)'].describe()

count    7671.000000
mean       -0.015252
std        17.033724
min      -198.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       206.000000
Name: Change In Snow Depth (in), dtype: float64

In [5]:
bins = [-340, -60, -12, -6, -3, 0,  3, 6, 12, 24, 60, 341]
labels = ['melting 28ft-5ft',' melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
         'melting 3in-0in', '0in-3in', '3in-6in', '6in-12in', '12in-24in', '2ft-5ft','5ft-28ft']
df['binned'] = pd.cut(df['Change In Snow Depth (in)'], bins=bins, labels=labels)
df

,Unnamed: 0,Unnamed: 0_x,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),...,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,binned
2562,2562,11144.0,2000-01-01,Buffalo Park,4.3,0.0,0.0,0.0,9240.0,17.0,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2563,2563,11145.0,2000-01-02,Buffalo Park,4.5,0.2,0.0,0.0,9240.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2564,2564,11146.0,2000-01-03,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,3.0,...,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2565,2565,11147.0,2000-01-04,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,13.0,...,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2566,2566,11148.0,2000-01-05,Buffalo Park,4.7,0.2,0.0,0.0,9240.0,12.0,...,0.1,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761812,761812,763457.0,2020-12-27,Buffalo Park,3.7,0.2,19.0,2.0,9240.0,16.0,...,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0in-3in
761813,761813,763458.0,2020-12-28,Buffalo Park,3.8,0.1,20.0,1.0,9240.0,15.0,...,0.4,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0in-3in
761814,761814,763459.0,2020-12-29,Buffalo Park,4.2,0.4,22.0,2.0,9240.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0in-3in
761815,761815,763460.0,2020-12-30,Buffalo Park,4.2,0.0,22.0,0.0,9240.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
761816,761816,763461.0,2020-12-31,Buffalo Park,4.2,0.0,22.0,0.0,9240.0,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in

In [6]:
# df['Change In Snow Depth (in)'].unique()

In [7]:
target = df['binned']
one_hot3 = pd.get_dummies(target)
target_names = ['melting 28ft-5ft',' melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
         'melting 3in-0in', '0in-3in', '3in-6in', '6in-12in', '12in-24in', '2ft-5ft','5ft-28ft']

In [8]:
one_hot3

,melting 28ft-5ft,melting 5ft-1ft,melting 12in-6in,melting 6in-3in,melting 3in-0in,0in-3in,3in-6in,6in-12in,12in-24in,2ft-5ft,5ft-28ft
2562,0,0,0,0,1,0,0,0,0,0,0
2563,0,0,0,0,1,0,0,0,0,0,0
2564,0,0,0,0,1,0,0,0,0,0,0
2565,0,0,0,0,1,0,0,0,0,0,0
2566,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
761812,0,0,0,0,0,1,0,0,0,0,0
761813,0,0,0,0,0,1,0,0,0,0,0
761814,0,0,0,0,0,1,0,0,0,0,0
761815,0,0,0,0,1,0,0,0,0,0,0
761816,0,0,0,0,1,0,0,0,0,0,0

In [9]:
target

2562      melting 3in-0in
2563      melting 3in-0in
2564      melting 3in-0in
2565      melting 3in-0in
2566      melting 3in-0in
               ...
761812            0in-3in
761813            0in-3in
761814            0in-3in
761815    melting 3in-0in
761816    melting 3in-0in
Name: binned, Length: 7671, dtype: category
Categories (11, object): [melting 28ft-5ft < melting 5ft-1ft < melting 12in-6in < melting 6in-3in ... 6in-12in < 12in-24in < 2ft-5ft < 5ft-28ft]

In [10]:
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df.head()

,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,...,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,binned
2562,2000-01-01,Buffalo Park,4.3,0.0,0.0,0.0,9240.0,17.0,40.22861,-106.59528,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2563,2000-01-02,Buffalo Park,4.5,0.2,0.0,0.0,9240.0,12.0,40.22861,-106.59528,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2564,2000-01-03,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,3.0,40.22861,-106.59528,...,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2565,2000-01-04,Buffalo Park,4.5,0.0,0.0,0.0,9240.0,13.0,40.22861,-106.59528,...,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2566,2000-01-05,Buffalo Park,4.7,0.2,0.0,0.0,9240.0,12.0,40.22861,-106.59528,...,0.1,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in

In [11]:
dates=df['Date'].astype('datetime64[ns]')
dates=dates.dt.dayofyear
df['Date']=dates
one_hot = pd.get_dummies(df['Station Name'])
one_hot2 = pd.get_dummies(df['binned'])
# Drop column as it is now encoded
df1 = df.drop(['Station Name'],axis = 1)
df1 = df1.drop(['binned'],axis = 1)
# Join the encoded df
testing_df = df1.join(one_hot)
testing_df = testing_df.join(one_hot2)

In [12]:
data = testing_df.drop(['Change In Snow Depth (in)','melting 28ft-5ft',' melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
         'melting 3in-0in', '0in-3in', '3in-6in', '6in-12in', '12in-24in', '2ft-5ft','5ft-28ft', 'County Name'], axis=1)
feature_names = data.columns
data.head()

,Date,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,Station Id,Air Temperature Observed (degF) Start of Day Values,...,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,Buffalo Park
2562,1,4.3,0.0,0.0,9240.0,17.0,40.22861,-106.59528,913,2.0,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2563,2,4.5,0.2,0.0,9240.0,12.0,40.22861,-106.59528,913,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2564,3,4.5,0.0,0.0,9240.0,3.0,40.22861,-106.59528,913,4.0,...,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2565,4,4.5,0.0,0.0,9240.0,13.0,40.22861,-106.59528,913,1.0,...,0.2,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2566,5,4.7,0.2,0.0,9240.0,12.0,40.22861,-106.59528,913,15.0,...,0.1,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [13]:
# data.round(6)

In [14]:
# pd.set_option('display.max_rows', 139)

In [15]:
data=data.drop(['Latitude','Longitude'], axis=1)

In [16]:
# list(data.dtypes)

In [17]:
data.astype(int)

,Date,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Elevation (ft),Air Temperature Average (degF),Station Id,Air Temperature Observed (degF) Start of Day Values,Barometric Pressure (inch_Hg) Start of Day Values,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,Buffalo Park
2562,1,4,0,0,9240,17,913,2,0,5,0,0,0,0,0,0,0,0,0,1
2563,2,4,0,0,9240,12,913,16,0,5,0,0,0,0,0,0,0,0,0,1
2564,3,4,0,0,9240,3,913,4,0,5,0,0,0,0,0,0,0,0,0,1
2565,4,4,0,0,9240,13,913,1,0,5,0,0,0,0,0,0,0,0,0,1
2566,5,4,0,0,9240,12,913,15,0,5,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
761812,362,3,0,19,9240,16,913,22,0,3,0,0,0,0,0,0,0,0,0,1
761813,363,3,0,20,9240,15,913,-3,0,3,0,0,0,0,0,0,0,0,0,1
761814,364,4,0,22,9240,12,913,21,0,4,0,0,0,0,0,0,0,0,0,1
761815,365,4,0,22,9240,2,913,-12,0,4,0,0,0,0,0,0,0,0,0,1
761816,366,4,0,22,9240,18,913,4,0,4,0,0,0,0,0,0,0,0,0,1

In [18]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(data, one_hot3, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [19]:
# X_test.fillna(X_test.mean())
# X_train.fillna(X_train.mean())

In [20]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_train, y_train)
# clf.score(X_test, y_test)

1.0

In [21]:
clf.score(X_test, y_test)

0.7898852971845672

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=20)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8347236704900939

In [23]:
y_test

635760    melting 3in-0in
310728            3in-6in
552308    melting 3in-0in
510993    melting 3in-0in
131216    melting 3in-0in
               ...
719668    melting 3in-0in
310801    melting 6in-3in
388910    melting 3in-0in
64901     melting 3in-0in
677511            0in-3in
Name: binned, Length: 1918, dtype: category
Categories (11, object): [melting 28ft-5ft < melting 5ft-1ft < melting 12in-6in < melting 6in-3in ... 6in-12in < 12in-24in < 2ft-5ft < 5ft-28ft]

In [24]:
predictions =clf.predict_proba(X_test)

In [25]:
print(predictions)
len(predictions)

[[0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

1918

In [26]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.18080985253915283, 'Change In Snow Water Equivalent (in)'),
 (0.18037362782038385, 'Snow Depth (in) Start of Day Values'),
 (0.12151529476815884, 'Date'),
 (0.11614901520787005, 'Air Temperature Average (degF)'),
 (0.11223750687008568, 'Snow Water Equivalent (in) Start of Day Values'),
 (0.11159593013518128, 'Air Temperature Observed (degF) Start of Day Values'),
 (0.10941823209998533, 'Longitude'),
 (0.03586887541613106, 'Precipitation Accumulation (in) Start of Day Values'),
 (0.03203166514305097, 'Barometric Pressure (inch_Hg) Start of Day Values'),
 (0.0, 'Station Id'),
 (0.0, 'Solar Radiation Average (watt/m2)'),
 (0.0, 'Soil Temperature Observed -8in (degF) Start of Day Values'),
 (0.0, 'Soil Temperature Observed -4in (degF) Start of Day Values'),
 (0.0, 'Soil Temperature Observed -2in (degF) Start of Day Values'),
 (0.0, 'Soil Temperature Observed -20in (degF) Start of Day Values'),
 (0.0, 'Precipitation Month-to-date (in)'),
 (0.0, 'Precipitation Increment - Snow-adj (in)'),
 (0.0, 'Precipitation Increment (in)'),
 (0.0, 'Latitude'),
 (0.0, 'Elevation (ft)')]

In [27]:
X_test.iloc[0]

Date                                                           247.0
Snow Water Equivalent (in) Start of Day Values                   0.0
Change In Snow Water Equivalent (in)                             0.0
Snow Depth (in) Start of Day Values                              0.0
Elevation (ft)                                                9240.0
Air Temperature Average (degF)                                  55.0
Station Id                                                     913.0
Air Temperature Observed (degF) Start of Day Values             39.0
Barometric Pressure (inch_Hg) Start of Day Values                0.0
Precipitation Accumulation (in) Start of Day Values             24.0
Precipitation Increment (in)                                     0.0
Precipitation Increment - Snow-adj (in)                          0.0
Precipitation Month-to-date (in)                                 0.0
Solar Radiation Average (watt/m2)                                0.0
Soil Temperature Observed -2in (degF) Start of Day Values        0.0
Soil Temperature Observed -4in (degF) Start of Day Values        0.0
Soil Temperature Observed -8in (degF) Start of Day Values        0.0
Soil Temperature Observed -20in (degF) Start of Day Values       0.0
Soil Temperature Observed -40in (degF) Start of Day Values       0.0
Buffalo Park                                                     1.0
Name: 635760, dtype: float64

In [28]:
X_test.columns

Index(['Date', 'Snow Water Equivalent (in) Start of Day Values',
       'Change In Snow Water Equivalent (in)',
       'Snow Depth (in) Start of Day Values', 'Elevation (ft)',
       'Air Temperature Average (degF)', 'Station Id',
       'Air Temperature Observed (degF) Start of Day Values',
       'Barometric Pressure (inch_Hg) Start of Day Values',
       'Precipitation Accumulation (in) Start of Day Values',
       'Precipitation Increment (in)',
       'Precipitation Increment - Snow-adj (in)',
       'Precipitation Month-to-date (in)', 'Solar Radiation Average (watt/m2)',
       'Soil Temperature Observed -2in (degF) Start of Day Values',
       'Soil Temperature Observed -4in (degF) Start of Day Values',
       'Soil Temperature Observed -8in (degF) Start of Day Values',
       'Soil Temperature Observed -20in (degF) Start of Day Values',
       'Soil Temperature Observed -40in (degF) Start of Day Values',
       'Buffalo Park'],
      dtype='object')

In [29]:
# import pickle
# clf_name='d_tree_range_modle.sav'
# rf_name='rf_range_model.sav'
# pickle.dump(clf, open(clf_name, 'wb'))
# pickle.dump(rf, open(rf_name, 'wb'))