In [1]:
from sklearn import tree
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_csv(os.path.join("../data/bulk_data.csv"))
# df=df.replace([np.inf, -np.inf], np.nan, inplace=True)
df=df.fillna(0)
df.head()

,Unnamed: 0,Unnamed: 0_x,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),...,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
0,0,0.0,2000-01-01,Apishapa,4.1,0.4,12.0,0.0,10000.0,24.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1.0,2000-01-02,Apishapa,4.1,0.0,12.0,0.0,10000.0,18.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2.0,2000-01-03,Apishapa,4.1,0.0,12.0,0.0,10000.0,6.0,...,7.4,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,3.0,2000-01-04,Apishapa,4.1,0.0,15.0,3.0,10000.0,21.0,...,7.7,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4.0,2000-01-05,Apishapa,4.5,0.4,14.0,-1.0,10000.0,24.0,...,7.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
# df=df[df['Station Name']== "Buffalo Park"]
# df

,Unnamed: 0,Unnamed: 0_x,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),...,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
0,0,0.0,2000-01-01,Apishapa,4.1,0.4,12.0,0.0,10000.0,24.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1.0,2000-01-02,Apishapa,4.1,0.0,12.0,0.0,10000.0,18.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2.0,2000-01-03,Apishapa,4.1,0.0,12.0,0.0,10000.0,6.0,...,7.4,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,3.0,2000-01-04,Apishapa,4.1,0.0,15.0,3.0,10000.0,21.0,...,7.7,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4.0,2000-01-05,Apishapa,4.5,0.4,14.0,-1.0,10000.0,24.0,...,7.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799144,799144,814836.0,2020-12-27,Zirkel,6.0,0.4,25.0,3.0,9340.0,19.0,...,9.0,0.2,0.2,0.0,0.0,33.0,0.0,34.0,35.0,0.0
799145,799145,814837.0,2020-12-28,Zirkel,6.2,0.2,31.0,6.0,9340.0,17.0,...,9.2,0.5,0.5,0.0,0.0,33.0,0.0,34.0,35.0,0.0
799146,799146,814838.0,2020-12-29,Zirkel,6.7,0.5,32.0,1.0,9340.0,16.0,...,9.7,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0
799147,799147,814839.0,2020-12-30,Zirkel,6.7,0.0,32.0,0.0,9340.0,15.0,...,9.7,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0
799148,799148,814840.0,2020-12-31,Zirkel,6.7,0.0,30.0,-2.0,9340.0,22.0,...,9.7,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0

In [4]:
df['Change In Snow Depth (in)'].describe()

count    799149.000000
mean         -0.014992
std          10.767195
min        -340.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         341.000000
Name: Change In Snow Depth (in), dtype: float64

In [152]:
bins = [-341, -60, -12, -6, -3, 0,  3, 6, 12, 24, 60, 342]
labels = ['melting 28ft-5ft', 'melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
         'melting 3in-0in', 'snowing 0in-3in', 'snowing 3in-6in', 'snowing 6in-12in', 
         'snowing 12in-24in', 'snowing 2ft-5ft','snowing 5ft-28ft']
df['binned'] = pd.cut(df['Change In Snow Depth (in)'], bins=bins, labels=labels)#.astype('O')
df

,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,...,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,binned
0,1,Apishapa,4.1,0.4,12.0,0.0,10000.0,24.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
1,1,Apishapa,4.1,0.0,12.0,0.0,10000.0,18.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2,1,Apishapa,4.1,0.0,12.0,0.0,10000.0,6.0,37.33062,-105.06749,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
3,1,Apishapa,4.1,0.0,15.0,3.0,10000.0,21.0,37.33062,-105.06749,...,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,snowing 0in-3in
4,1,Apishapa,4.5,0.4,14.0,-1.0,10000.0,24.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799144,1,Zirkel,6.0,0.4,25.0,3.0,9340.0,19.0,40.79488,-106.59535,...,0.2,0.2,0.0,0.0,33.0,0.0,34.0,35.0,0.0,snowing 0in-3in
799145,1,Zirkel,6.2,0.2,31.0,6.0,9340.0,17.0,40.79488,-106.59535,...,0.5,0.5,0.0,0.0,33.0,0.0,34.0,35.0,0.0,snowing 3in-6in
799146,1,Zirkel,6.7,0.5,32.0,1.0,9340.0,16.0,40.79488,-106.59535,...,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0,snowing 0in-3in
799147,1,Zirkel,6.7,0.0,32.0,0.0,9340.0,15.0,40.79488,-106.59535,...,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0,melting 3in-0in
799148,1,Zirkel,6.7,0.0,30.0,-2.0,9340.0,22.0,40.79488,-106.59535,...,0.0,0.0,0.0,0.0,33.0,0.0,34.0,35.0,0.0,melting 3in-0in

In [153]:
# df['Change In Snow Depth (in)'].unique()

In [154]:
target = df['binned']
# one_hot3 = pd.get_dummies(target)
# target_names = ['melting 28ft-5ft',' melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
#          'melting 3in-0in', 'snowing 0in-3in', ' snowing 3in-6in', 'snowing 6in-12in', 'snowing 12in-24in', 'snowing 2ft-5ft','snowing 5ft-28ft']

In [155]:
one_hot3

,melting 28ft-5ft,melting 5ft-1ft,melting 12in-6in,melting 6in-3in,melting 3in-0in,snowing 0in-3in,snowing 3in-6in,snowing 6in-12in,snowing 12in-24in,snowing 2ft-5ft,snowing 5ft-28ft
0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
799144,0,0,0,0,0,1,0,0,0,0,0
799145,0,0,0,0,0,0,1,0,0,0,0
799146,0,0,0,0,0,1,0,0,0,0,0
799147,0,0,0,0,1,0,0,0,0,0,0
799148,0,0,0,0,1,0,0,0,0,0,0

In [156]:
target.dtype

CategoricalDtype(categories=['melting 28ft-5ft', 'melting 5ft-1ft', 'melting 12in-6in',
                  'melting 6in-3in', 'melting 3in-0in', 'snowing 0in-3in',
                  'snowing 3in-6in', 'snowing 6in-12in', 'snowing 12in-24in',
                  'snowing 2ft-5ft', 'snowing 5ft-28ft'],
                 ordered=True)

In [157]:
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df.head()

,Date,Station Name,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Change In Snow Depth (in),Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,...,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values,binned
0,1,Apishapa,4.1,0.4,12.0,0.0,10000.0,24.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
1,1,Apishapa,4.1,0.0,12.0,0.0,10000.0,18.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
2,1,Apishapa,4.1,0.0,12.0,0.0,10000.0,6.0,37.33062,-105.06749,...,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in
3,1,Apishapa,4.1,0.0,15.0,3.0,10000.0,21.0,37.33062,-105.06749,...,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,snowing 0in-3in
4,1,Apishapa,4.5,0.4,14.0,-1.0,10000.0,24.0,37.33062,-105.06749,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,melting 3in-0in

In [158]:
dates=df['Date'].astype('datetime64[ns]')
dates=dates.dt.dayofyear
df['Date']=dates
# one_hot = pd.get_dummies(df['Station Name'])
one_hot2 = pd.get_dummies(df['binned'])
# Drop column as it is now encoded
df1 = df.drop(['Station Name','County Name'],axis = 1)
df1 = df1.drop(['binned'],axis = 1)
# Join the encoded df
# testing_df = df1.join(one_hot)
testing_df = df1.join(one_hot2)

In [159]:
data = testing_df.drop(['Change In Snow Depth (in)','melting 28ft-5ft','melting 5ft-1ft','melting 12in-6in', 'melting 6in-3in',
         'melting 3in-0in', 'snowing 0in-3in', 'snowing 3in-6in', 'snowing 6in-12in', 'snowing 12in-24in', 'snowing 2ft-5ft','snowing 5ft-28ft'], axis=1)
feature_names = data.columns
data.head()

,Date,Snow Water Equivalent (in) Start of Day Values,Change In Snow Water Equivalent (in),Snow Depth (in) Start of Day Values,Elevation (ft),Air Temperature Average (degF),Latitude,Longitude,Station Id,Air Temperature Observed (degF) Start of Day Values,...,Precipitation Accumulation (in) Start of Day Values,Precipitation Increment (in),Precipitation Increment - Snow-adj (in),Precipitation Month-to-date (in),Solar Radiation Average (watt/m2),Soil Temperature Observed -2in (degF) Start of Day Values,Soil Temperature Observed -4in (degF) Start of Day Values,Soil Temperature Observed -8in (degF) Start of Day Values,Soil Temperature Observed -20in (degF) Start of Day Values,Soil Temperature Observed -40in (degF) Start of Day Values
0,1,4.1,0.4,12.0,10000.0,24.0,37.33062,-105.06749,303,31.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,4.1,0.0,12.0,10000.0,18.0,37.33062,-105.06749,303,19.0,...,7.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,4.1,0.0,12.0,10000.0,6.0,37.33062,-105.06749,303,13.0,...,7.4,0.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,4.1,0.0,15.0,10000.0,21.0,37.33062,-105.06749,303,1.0,...,7.7,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,4.5,0.4,14.0,10000.0,24.0,37.33062,-105.06749,303,27.0,...,7.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [160]:
# data.round(6)

In [161]:
# pd.set_option('display.max_rows', 139)

In [162]:
data=data.drop(['Latitude','Longitude'], axis=1)

In [163]:
# list(data.dtypes)

In [164]:
data=data.astype(int)

In [165]:
data.columns

Index(['Date', 'Snow Water Equivalent (in) Start of Day Values',
       'Change In Snow Water Equivalent (in)',
       'Snow Depth (in) Start of Day Values', 'Elevation (ft)',
       'Air Temperature Average (degF)', 'Station Id',
       'Air Temperature Observed (degF) Start of Day Values',
       'Barometric Pressure (inch_Hg) Start of Day Values',
       'Precipitation Accumulation (in) Start of Day Values',
       'Precipitation Increment (in)',
       'Precipitation Increment - Snow-adj (in)',
       'Precipitation Month-to-date (in)', 'Solar Radiation Average (watt/m2)',
       'Soil Temperature Observed -2in (degF) Start of Day Values',
       'Soil Temperature Observed -4in (degF) Start of Day Values',
       'Soil Temperature Observed -8in (degF) Start of Day Values',
       'Soil Temperature Observed -20in (degF) Start of Day Values',
       'Soil Temperature Observed -40in (degF) Start of Day Values'],
      dtype='object')

In [166]:
target.dtype

CategoricalDtype(categories=['melting 28ft-5ft', 'melting 5ft-1ft', 'melting 12in-6in',
                  'melting 6in-3in', 'melting 3in-0in', 'snowing 0in-3in',
                  'snowing 3in-6in', 'snowing 6in-12in', 'snowing 12in-24in',
                  'snowing 2ft-5ft', 'snowing 5ft-28ft'],
                 ordered=True)

In [167]:
# X_test.fillna(X_test.mean())
# X_train.fillna(X_train.mean())

In [168]:
target.dtype#.value_counts()

CategoricalDtype(categories=['melting 28ft-5ft', 'melting 5ft-1ft', 'melting 12in-6in',
                  'melting 6in-3in', 'melting 3in-0in', 'snowing 0in-3in',
                  'snowing 3in-6in', 'snowing 6in-12in', 'snowing 12in-24in',
                  'snowing 2ft-5ft', 'snowing 5ft-28ft'],
                 ordered=True)

In [169]:
from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder
# lb=LabelEncoder()
# target=lb.fit_transform(target)
X_train, X_test, y_train, y_test=train_test_split(data, target, random_state=42)

In [174]:
X_train.columns

Index(['Date', 'Snow Water Equivalent (in) Start of Day Values',
       'Change In Snow Water Equivalent (in)',
       'Snow Depth (in) Start of Day Values', 'Elevation (ft)',
       'Air Temperature Average (degF)', 'Station Id',
       'Air Temperature Observed (degF) Start of Day Values',
       'Barometric Pressure (inch_Hg) Start of Day Values',
       'Precipitation Accumulation (in) Start of Day Values',
       'Precipitation Increment (in)',
       'Precipitation Increment - Snow-adj (in)',
       'Precipitation Month-to-date (in)', 'Solar Radiation Average (watt/m2)',
       'Soil Temperature Observed -2in (degF) Start of Day Values',
       'Soil Temperature Observed -4in (degF) Start of Day Values',
       'Soil Temperature Observed -8in (degF) Start of Day Values',
       'Soil Temperature Observed -20in (degF) Start of Day Values',
       'Soil Temperature Observed -40in (degF) Start of Day Values'],
      dtype='object')

In [170]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_train, y_train)
# clf.score(X_test, y_test)

0.9989538858884712

In [171]:
clf.score(X_test, y_test)

0.7600856908322822

In [172]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=20)
rf = rf.fit(X_train, y_train)

In [173]:
rf.score(X_test, y_test)

0.8208200692734299

In [56]:
y_train

284620     melting 3in-0in
579554     melting 3in-0in
189484     melting 3in-0in
571195     melting 3in-0in
769116     melting 3in-0in
                ...
259178     melting 3in-0in
365838     melting 3in-0in
131932    melting 12in-6in
671155     melting 3in-0in
121958     melting 3in-0in
Name: binned, Length: 599361, dtype: category
Categories (11, object): [melting 28ft-5ft < melting 5ft-1ft < melting 12in-6in < melting 6in-3in ... snowing 6in-12in < snowing 12in-24in < snowing 2ft-5ft < snowing 5ft-28ft]

In [65]:
predictions =clf.predict_proba(X_test)

In [66]:
print(predictions)
len(predictions)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

199788

In [68]:
#displays unique values in the list of lists
unique_data = [list(x) for x in set(tuple(x) for x in predictions)]
unique_data

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [37]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.19863745461414492, 'Snow Depth (in) Start of Day Values'),
 (0.14464222164104654, 'Date'),
 (0.11625363364174598, 'Air Temperature Average (degF)'),
 (0.11574029970330356, 'Longitude'),
 (0.0822724300289087, 'Air Temperature Observed (degF) Start of Day Values'),
 (0.08216342834730328, 'Latitude'),
 (0.07908060377739069, 'Snow Water Equivalent (in) Start of Day Values'),
 (0.07815770359997797, 'Elevation (ft)'),
 (0.027802641453750825, 'Change In Snow Water Equivalent (in)'),
 (0.019049088377643204,
  'Soil Temperature Observed -4in (degF) Start of Day Values'),
 (0.018600296165361505,
  'Soil Temperature Observed -2in (degF) Start of Day Values'),
 (0.01816636855377213, 'Precipitation Month-to-date (in)'),
 (0.007103324853663002, 'Solar Radiation Average (watt/m2)'),
 (0.006155564540748765,
  'Soil Temperature Observed -8in (degF) Start of Day Values'),
 (0.0027101468469408903,
  'Precipitation Accumulation (in) Start of Day Values'),
 (0.0017392131096981627, 'Barometric Pressure (inch_Hg) Start of Day Values'),
 (0.0017255807446000175, 'Precipitation Increment - Snow-adj (in)'),
 (0.0, 'Station Id'),
 (0.0, 'Precipitation Increment (in)')]

In [69]:
y_test

59215     melting 3in-0in
375142    melting 3in-0in
696404    melting 3in-0in
323840    melting 3in-0in
705503    melting 3in-0in
               ...
20833     melting 3in-0in
10404     melting 3in-0in
91485     melting 3in-0in
686417    melting 3in-0in
459046    melting 3in-0in
Name: binned, Length: 199788, dtype: category
Categories (11, object): [melting 28ft-5ft < melting 5ft-1ft < melting 12in-6in < melting 6in-3in ... snowing 6in-12in < snowing 12in-24in < snowing 2ft-5ft < snowing 5ft-28ft]

In [39]:
X_test.iloc[0]

Date                                                            127
Snow Water Equivalent (in) Start of Day Values                   33
Change In Snow Water Equivalent (in)                              0
Snow Depth (in) Start of Day Values                               0
Elevation (ft)                                                10200
Air Temperature Average (degF)                                   37
Station Id                                                      840
Air Temperature Observed (degF) Start of Day Values              21
Barometric Pressure (inch_Hg) Start of Day Values                 0
Precipitation Accumulation (in) Start of Day Values              44
Precipitation Increment (in)                                      0
Precipitation Increment - Snow-adj (in)                           0
Precipitation Month-to-date (in)                                  0
Solar Radiation Average (watt/m2)                                 0
Soil Temperature Observed -2in (degF) Start of Day Values         0
Soil Temperature Observed -4in (degF) Start of Day Values         0
Soil Temperature Observed -8in (degF) Start of Day Values         0
Soil Temperature Observed -20in (degF) Start of Day Values        0
Soil Temperature Observed -40in (degF) Start of Day Values        0
Name: 59215, dtype: int32

In [40]:
X_test.columns

Index(['Date', 'Snow Water Equivalent (in) Start of Day Values',
       'Change In Snow Water Equivalent (in)',
       'Snow Depth (in) Start of Day Values', 'Elevation (ft)',
       'Air Temperature Average (degF)', 'Station Id',
       'Air Temperature Observed (degF) Start of Day Values',
       'Barometric Pressure (inch_Hg) Start of Day Values',
       'Precipitation Accumulation (in) Start of Day Values',
       'Precipitation Increment (in)',
       'Precipitation Increment - Snow-adj (in)',
       'Precipitation Month-to-date (in)', 'Solar Radiation Average (watt/m2)',
       'Soil Temperature Observed -2in (degF) Start of Day Values',
       'Soil Temperature Observed -4in (degF) Start of Day Values',
       'Soil Temperature Observed -8in (degF) Start of Day Values',
       'Soil Temperature Observed -20in (degF) Start of Day Values',
       'Soil Temperature Observed -40in (degF) Start of Day Values'],
      dtype='object')

In [175]:
import pickle
clf_name='d_tree_range_modle_4.sav'
rf_name='rf_range_model_4.sav'
pickle.dump(clf, open(clf_name, 'wb'))
pickle.dump(rf, open(rf_name, 'wb'))